Cluddy\Bundle\CoreBundle\Entity\Person:
    type: mappedSuperclass
    gedmo:
        soft_deleteable:
            field_name: deletedAt
        loggable:
            logEntryClass: Gedmo\Loggable\Entity\LogEntry   
    fields:
        firstname:
           type: string
           length: 255
        lastname:
           type: string
           length: 255
        created:
            type: date
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: date
            nullable: true                    