parameters:
#    cluddy_core.example.class: Cluddy\Bundle\CoreBundle\Example

services:
#    cluddy_core.example:
#        class: %cluddy_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
